# Generated by Django 4.1.2 on 2022-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_alter_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="img",
            field=models.FileField(blank=True, upload_to="img"),
        ),
    ]
